### ISSUE TITLE
不能运行，修改后得不到数据

### ISSUE THREAD

**Issue by yehang515** [ecitlm/SpliderApi#10]
module.js:457
    throw err;
    ^

Error: Cannot find module 'html-entities'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kyle/node/SpliderApi/routes/api/job/job_info.js:13:42)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

bogon:SpliderApi kyle$ node app.js
app start success port:3001
[query] - :Error: connect ECONNREFUSED 127.0.0.1:3306

**Comment by ecitlm** [comment]
Error: Cannot find module 'html-entities'npm install html-entitie

**Comment by ecitlm** [comment]
npm install html-entities这个模块

https://www.npmjs.com/package/html-entities

**Comment by ecitlm** [comment]
`"html-entities": "^1.2.1"`,  你可以更新 `package.json`
